### ISSUE TITLE
Todo List

### ISSUE THREAD

**Issue by natir** [natir/variantplaner#1]
# Input/Output

- [X] Read vcf
- [X] Read sample name
- [X] Extract info information
- [x] Extract sample information
- [X] Write variant for LazyFrame
   * [x] chr, pos, ref, alt
   * [x] variant id
   * [x] quality
   * [x] filter
   * [x] info 
   * [x] format
   * [x] sample
- [X] Read csv
- [X] Write csv (polars)
- [X] Read json (polars)
- [X] Write json (polars)
- [x] Write partitionate genotype

# Manage data

- [x] Extract variant
- [x] Extract genotype:
- [x] Extract info
- [X] Partitionate genotype
- [X] Join LazyFrame (polars)
- [X] Group by LazyFrame (polars)
- [X] Filter LazyFrame (polars)

# CLI

- [x] vcf2parquet
- [x] parquet2vcf
- [x] struct
  * [x] variant
  * [X] genotype
- [x] metadata
- [x] annotations

# CI

- [x] Write test for all
  * [x] subcommand
     + [x] vcf2parquet
     + [x] struct
     + [x] annotations
     + [x] metadata      
  * [x] exception
  * [x] io
     + [x] csv
     + [x] vcf
  * [x] manipulation
  * [x] structuration
  
# Documentation

- [x] Proofreading
  * [X] Reame.md
  * [x] Documentation
    + [x] cli
    + [x] exception
    + [x] extract
    + [x] generate
    + [x] io
    + [x] io.csv
    + [x] io.ped
    + [x] vcf
    + [x] normalization
    + [x] struct
    + [x] struct.genotypes
    + [x] struct.variants
  * [x] Command help
     + [x] main
     + [x] annotations
     + [x] generate
     + [x] metadata
     + [x] parquet2vcf
     + [x] struct
     + [x] vcf2parquet

- [x] Small real case usage
  * [x] Download data
  * [x] Perform pipeline
  * [x] Example of request:
     + [X] polars-cli
     + [x] duckdb
